<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#The-Python-Programming-Language:-Variables-and-Types" data-toc-modified-id="The-Python-Programming-Language:-Variables-and-Types-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>The Python Programming Language: Variables and Types</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Operations-with-strings" data-toc-modified-id="Operations-with-strings-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Operations with strings</a></span></li><li><span><a href="#Functions" data-toc-modified-id="Functions-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>Functions</a></span></li><li><span><a href="#Conditional-statements" data-toc-modified-id="Conditional-statements-1.0.3"><span class="toc-item-num">1.0.3&nbsp;&nbsp;</span>Conditional statements</a></span></li></ul></li></ul></li><li><span><a href="#The-Python-Programming-Language:-Advanced-Types" data-toc-modified-id="The-Python-Programming-Language:-Advanced-Types-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The Python Programming Language: Advanced Types</a></span><ul class="toc-item"><li><span><a href="#Lists" data-toc-modified-id="Lists-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Lists</a></span></li><li><span><a href="#Tuples" data-toc-modified-id="Tuples-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Tuples</a></span></li><li><span><a href="#Dictionaries" data-toc-modified-id="Dictionaries-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Dictionaries</a></span></li></ul></li><li><span><a href="#The-Python-Programming-Language:-Dates-and-Times" data-toc-modified-id="The-Python-Programming-Language:-Dates-and-Times-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>The Python Programming Language: Dates and Times</a></span></li><li><span><a href="#The-Python-Programming-Language:-Lambda-and-List-Comprehensions" data-toc-modified-id="The-Python-Programming-Language:-Lambda-and-List-Comprehensions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>The Python Programming Language: Lambda and List Comprehensions</a></span></li><li><span><a href="#The-Python-Programming-Language:-Numerical-Python-(NumPy)" data-toc-modified-id="The-Python-Programming-Language:-Numerical-Python-(NumPy)-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>The Python Programming Language: Numerical Python (NumPy)</a></span><ul class="toc-item"><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Creating Arrays</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Math-Functions" data-toc-modified-id="Math-Functions-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Math Functions</a></span></li><li><span><a href="#Indexing-/-Slicing" data-toc-modified-id="Indexing-/-Slicing-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Indexing / Slicing</a></span></li><li><span><a href="#Copying-Data" data-toc-modified-id="Copying-Data-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Copying Data</a></span><ul class="toc-item"><li><span><a href="#Iterating-Over-Arrays" data-toc-modified-id="Iterating-Over-Arrays-5.5.1"><span class="toc-item-num">5.5.1&nbsp;&nbsp;</span>Iterating Over Arrays</a></span></li></ul></li></ul></li></ul></div>

# The Python Programming Language: Variables and Types

In [1]:
x = 1
y = 2
print(x + y)
print(x*y)

3
2


In [2]:
y3=5
print(y3)

5


In [2]:
x

1

In [3]:
y2 = 43
y2

43

this is **text**

In [7]:
print (x,y,type(x), type(y))  #use print for multiple outputs

1 2 <class 'int'> <class 'int'>


In [8]:
x=1.
y=2.
z = x/y
print(type(x))
print (z)
print (type(z))

<class 'float'>
0.5
<class 'float'>


In [10]:
type(False)

bool

In [11]:
s='this is a string'
print (s)
print (type(s))

this is a string
<class 'str'>


<br>
Now let's look at strings. Use bracket notation to slice a string.

In [12]:
print(s[0]) #first character, python indexing starts from 0
print(s[0:2]) #first character, the last index (1) is not included
print(s[0:4]) #first two characters, the last index (2) is not included


t
th
this


In [13]:
print (s[-1])
# the last character
print (s[-4:-2])  # slice starting from the 4th element from the end and stopping before the 2nd element from the end
print (s[3:])    # slice starting from the 3rd element of the string and going all the way to the end

g
ri
s is a string


### Operations with strings

In [15]:
firstname = 'Jean'
lastname = "Dupont"   # You can either use quotes or double quotes for strings

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)
print('Jea' in firstname)

Jean Dupont
JeanJeanJean
False
True


In [17]:
fullname= 'Jean Dupont'
fullname.split('D')  # Split the string on the space character

['Jean ', 'upont']

In [18]:
'Jean'+ 2

TypeError: Can't convert 'int' object to str implicitly

In [19]:
'Jean'+ str(2) # Make sure you convert objects to strings before concatenating

'Jean2'

<br>
Python has a built in method for convenient string formatting.

In [27]:
price = 3.24
num_items = 5
year = 2018
print('the price for the year ',year,' is',price)
print("the price is %i" %num_items)
print("the price is %f" %price)
print("the price for the year %i is %f" %(year,price))
print('Jean bought {} item(s) at a price of {} each for a total of {}'.format(num_items, price, num_items*price))

the price for the year  2018  is 3.24
the price is 5
the price is 3.240000
the price for the year 2018 is 3.240000
Jean bought 5 item(s) at a price of 3.24 each for a total of 16.200000000000003


### Functions

In [32]:
# add_numbers is a function that takes two numbers and adds them together.
def add_numbers(x1, x2):
    return x1 + x2

t=add_numbers(1, 2)
print(t)

def printing():
    print('test')
printing()

3
test


In [29]:
# A function can be  assigned to a variable 
def add_numbers(x1, x2):
    z= x1 + x2
    return z

a = add_numbers
a(1,2)

3

### Conditional statements

In [33]:
x1 = 2
x2 = 7
if x1 > 5:
    print ('x1 is greater than 5')
else:
    print ('x1 is smaller than 5')

x1 is smaller than 5


In [34]:
if x1> 5 and x2 > 5:
    print ('x1 and x2 are greater than 5')
elif x1 > 5 or x2 >5:
    print ('x1 or x2 is greater than 5')
else:
    print ('x1 and x2 are smaller than 5')

x1 or x2 is greater than 5


<br>
# The Python Programming Language: Advanced Types

## Lists

In [44]:
x = [1, 'a', 2, 'hello', 3, True]  # Use brackets
print(x)
print (type(x))

[1, 'a', 2, 'hello', 3, True]
<class 'list'>


<br>
Lists are indexed in the same way as strings

In [39]:
print (x[0])
print (x[1:3])
print (x[-2:])
print (x[-1])
print (x[::-1])

1
['a', 2]
[3, True]
True
[True, 3, 'hello', 2, 'a', 1]


<br>
Lists are a mutable data structure ==> changed after création

In [46]:
x.append(3.3)  # Use append to append an object to a list
print (x)
x[0] = -1    # Change the value of the first element from 1 to -1
print (x)

[1, 'a', 2, 'hello', 3, True, 3.3, 3.3]
[-1, 'a', 2, 'hello', 3, True, 3.3, 3.3]


<br>
This is an example of how to loop through each item in the list.

In [47]:
for blabla in x:
    print(blabla)

-1
a
2
hello
3
True
3.3
3.3


In [49]:
print ([1,2] + [3,4])   # Use + to concatenate lists
print ([1]*3)  # Use * to repeat lists
print (1 in [1, 2, 3])  # Use the in operator to check if something is inside a list
print ('Mimo' in ['Kimo', 'Mimo', 'dodo'])  # Use the in operator to check if something is inside a list

[1, 2, 3, 4]
[1, 1, 1]
True
True


## Tuples

In [50]:
t = (1, 'a', 2, 'hello', 3, True)  # Use parenthesis
print (t, type(t))

(1, 'a', 2, 'hello', 3, True) <class 'tuple'>


<br>
Tuples are indexed in the same way as strings, lists

In [51]:
print (t[0])
print (t[1:3])
print (t[-2:])

1
('a', 2)
(3, True)


<br>
Tuples are an immutable data structure ==> cannot be altered

In [52]:
t[0] = -1

TypeError: 'tuple' object does not support item assignment

## Dictionaries 
Dictionaries associate keys with values.

In [54]:
d = {'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr', 'Hakim Idjis': 'hakim.idjis@edu.ece.fr'}  # Use curly brackets
print(d)
print (d, type(d))

{'Hakim Idjis': 'hakim.idjis@edu.ece.fr', 'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr'}
{'Hakim Idjis': 'hakim.idjis@edu.ece.fr', 'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr'} <class 'dict'>


<br>
Dictionaries are not indexed in the same way as strings, lists or tuples, we use the keys instead

In [55]:
d['Toufic Zaraket'] # Retrieve a value by using the indexing operator

'toufic.zaraket@edu.ece.fr'

<br>
Retrieve the keys

In [58]:
#for toto in d:   
#    print(toto)

# You can also use: for email in d.keys()

for blabla in d.keys():
    print(blabla)
    

Hakim Idjis
Toufic Zaraket


<br>
Retrieve the values:

In [63]:
#for blabla in d:
#    print(d[blabla])
    
# An other way of doing the same thing
#print ('****** 2nd method ***********')

for blabla in d.keys():
   print(blabla)
print( '*'*50)
for toto in d.values():
    print(toto)

Hakim Idjis
Toufic Zaraket
**************************************************
hakim.idjis@edu.ece.fr
toufic.zaraket@edu.ece.fr


<br>
Iterate over all of the items in the list:

In [64]:
for key, value in d.items():
    print(key,':',value)
    #print(email)

#print ('*'*50)
#for toto in d:
#    print(toto,',',d[toto])


Hakim Idjis : hakim.idjis@edu.ece.fr
Toufic Zaraket : toufic.zaraket@edu.ece.fr


<br>
# The Python Programming Language: Dates and Times

In [65]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [66]:
print(tm.time())
print(dt.datetime.now())

1515780547.4572024
2018-01-12 19:09:07.457202


<br>
Convert the timestamp to datetime.

In [67]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 1, 12, 19, 9, 55, 454948)

<br>
Handy datetime attributes:

In [68]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2018, 1, 12, 19, 9, 55)

In [72]:
print(dtnow.month)

dtnow.strftime('%b')

1


'Jan'

<br>
`timedelta` is a duration expressing the difference between two dates.

In [74]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
print(type(delta))
print(delta)

<class 'datetime.timedelta'>
100 days, 0:00:00


<br>
`date.today` returns the current local date.

In [75]:
today = dt.date.today()
print(today)
print(type(today))

2018-01-12
<class 'datetime.date'>


In [76]:
today - delta # the date 100 days ago

datetime.date(2017, 10, 4)

In [77]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [79]:
my_function = lambda a, b, c : a + b

In [80]:
my_function(1, 2, 3)

3

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [86]:
#my_list= list()
my_list = []
for number in range(0, 20):
    if number % 3 == 0:
        my_list.append(number)
print('my_list contins the following items:',my_list)

my_list contins the following items: [0, 3, 6, 9, 12, 15, 18]


<br>
Now the same thing but with list comprehension.

In [87]:
my_list = [number for number in range(0,20) if number % 3 == 0]
my_list

[0, 3, 6, 9, 12, 15, 18]

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [88]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [90]:
mylist = [1, 2, 3]
x = np.array(mylist)
y = np.array([1,2,3])
x
y

array([1, 2, 3])

<br>
Or just pass in a list directly

In [91]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [92]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [95]:
m = m.reshape(3,2)

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [96]:
m.shape

(3, 2)

<br>
`arange` returns evenly spaced values within a given interval.

In [104]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [105]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [108]:
o = np.linspace(0, 10, 4) # return 9 evenly spaced values from 0 to 4
o

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [109]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [111]:
np.zeros((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [112]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
Create an array using repeating list

In [113]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [114]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [115]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

<br>
Use `.dtype` to see the data type of the elements in the array.

In [ ]:
x.dtype

<br>
Use `.astype` to cast to a specific type.

In [ ]:
x = x.astype('f')
x.dtype

In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [116]:
a = np.array([-4, -2, 1, 3, 5])

In [117]:
a.sum()

3

In [118]:
a.max()

5

In [119]:
a.min()

-4

In [120]:
a.mean()

0.59999999999999998

In [121]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [ ]:
a.argmax()

In [ ]:
a.argmin()

<br>
## Indexing / Slicing

In [ ]:
s = np.arange(13)**2
s

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [ ]:
s[0], s[4], s[-1]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [ ]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

<br>
Use bracket notation to slice: `array[row, column]`

In [ ]:
r[2, 2]

<br>
And use : to select a range of rows or columns

In [ ]:
r[3, 3:6]

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [ ]:
r[:2, :-1]

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [ ]:
r[r > 30]

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [ ]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [ ]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [ ]:
r2[:] = 0
r2

<br>
`r` has also been changed!

In [ ]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [ ]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [ ]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [ ]:
test = np.random.randint(0, 10, (4,3))  # Generate a random integer in range 0-9 into a 4*3 array
test

In [ ]:
test = np.random.randint(0, 10, 2)  # Generate a random integer in range 0-9 into a 4*3 array
print(test)

<br>
Iterate by row:

In [ ]:
for row in test:
    print(row)

<br>
Iterate by index:

In [ ]:
print (test.shape)
for i in range(test.shape[0]):
    print(test[i])

<br>
Iterate by row and index:

In [ ]:
for i, row in enumerate(test):
    print('row', i, 'is', row)